language: node_js
node_js:
  - "10.x"
script:
  - npm run build
  - firebase deploy
install:
  - npm install
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project arise-team-webapp --token $FIREBASE_TOKEN
